name: picamera2 smoke tests

on:
  pull_request:
    branches: [ main, next ]

jobs:
  run-test:

    runs-on: ${{matrix.device}}

    strategy:
      matrix:
        device: [ pi4-1, pi5-2 ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        clean: true

    - name: Test
      run: DISPLAY=:0 PYTHONPATH=/home/pi/_work/picamera2/picamera2:/home/pi/libcamera/build/src/py:/home/pi/kmsxx/build/py:/home/pi/python-v4l2 python3 ${{github.workspace}}/tools/run_tests.py -p ${{github.workspace}}
      timeout-minutes: 30
